### ISSUE TITLE
A way to turn on and off the mod without restarting and a slider for the chance to him to spawn

### ISSUE THREAD

**Issue by Infernogd** [NicknameGG/robtop-jumpscare#4]
This not really a issue just a way to toggle the mod on and off without restarting would be nice and also a slider for the chance to him to spawn in the mods settings. Would be cool to add.

**Comment by NicknameGG** [comment]
I guess you can do it now with the slider set at 0%

**Comment by InfernoZv** [comment]
what slider only see the the 1% to randomise jumpscare
![image](https://github.com/NicknameGG/robtop-jumpscare/assets/164727301/10bf732e-3464-40da-9f46-458da791396c)
something like this would be help example: 
![image](https://github.com/NicknameGG/robtop-jumpscare/assets/164727301/b4de2ef8-afab-471b-a042-5ae467e570b9)

**Comment by NicknameGG** [comment]
Yeah, the latest PR added a slider but I forgot to update the mod in the index 💀

**Comment by InfernoZv** [comment]
oh ok will it be updated in the future?

**Comment by InfernoZv** [comment]
thanks for updating it!!!
