### ISSUE TITLE
tiny bug

### ISSUE THREAD

**Issue by Infernogd** [NicknameGG/robtop-jumpscare#7]
when the mod is installed the jumps in stats don't update just a tiny bug
![image](https://github.com/NicknameGG/robtop-jumpscare/assets/164727301/87d4a004-7540-4041-b435-24342b088d14)

**Comment by NicknameGG** [comment]
Ah, i forgot to call the original function, will fix next update!

**Comment by NicknameGG** [comment]
Fixed!
