### ISSUE TITLE
v1.3.3 breaks the mod (does not load)

### ISSUE THREAD

**Issue by himekode** [NicknameGG/robtop-jumpscare#8]
Tested on Android only

When I update the mod from v1.3.2 to v1.3.3, the mod does not load anymore. Geode will keep telling that there are "errors on some mods", yet when showing the mods with errors only, "No mods found", and that is because this mod failed to load. When going to the download list, it constantly says to get it.

This is why I am forced to stay in v1.3.2 to keep the mod loaded, but I do not like Geode to keep telling me that there are updates.

Thanks!

**Comment by NicknameGG** [comment]
This is weird, I admit I didn't check the mod on Android before releasing. I will check to see if i can reproduce the error

**Comment by fbfnysnshnsgnwg** [comment]
Also does not load on PC
